### ISSUE TITLE
Cell seperators in the output script should be customizable

### ISSUE THREAD

**Issue by Fraznist** [hasan-yaman/exporter#1]
Apart from general customizability, this would also help IDE's like vscode run jupyter notebooks over python scripts.

In vscode, users can seperate a python scripts into cells with a special line comment (`# %%`). Then vscode launches a jupyter server and enables users to execute these cells one by one in the jupyter server.

Essentially, this means we can use exporter to translate traditional .ipynb files to vscode-jupyter compatible scripts, and continue ourr notebook workflow in vscode.

**Comment by hasan-yaman** [comment]
Great idea @Fraznist 
Can you add this functionality? Currently, I am working on another feature. 

I think you can add a parameter to **export** function something like **cell_seperator**. The default value should be the newline character. Also, don't forget to add the same parameter to **console_script.py**

**Comment by hasan-yaman** [comment]
Solved #3
